---
#Ubuntu
- name: Update apt cache.
  apt: update_cache=true cache_valid_time=3600
  when: ansible_os_family == 'Debian'
  changed_when: false

- name: Install OpenJDK Java
  become: yes
  apt:
    name: openjdk-8-jdk
    state: present 
  when: ansible_os_family == 'Debian'

- name: Set the java_packages variable (Debian).
  set_fact:
    java_packages:
      - openjdk-8-jdk
#or      - openjdk-11-jdk
  when: ansible_os_family == 'Debian'
