apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-claim
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deploy
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:      
      initContainers:
      - name: take-data-dir-ownership
        image: alpine:3.6
        command:
        - chown
        - -R  
        - 1000:1000
        - /var/jenkins_home
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
          name: jenkins
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home

      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins-svc-ui
  namespace: jenkins
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: ui
  selector:
    app: jenkins
  type: LoadBalancer
