- name: Create group
  group:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ user_group }}'

- name: Create user
  user:
    name: '{{ user.name }}'
    group: '{{ user.group }}'
    shell: '{{ user.shell }}'
    state: present
  with_items:
    - name: '{{ user_name }}'
      group: '{{ user_group }}'
      shell: '{{ user_shell }}'
  loop_control:
    loop_var: user
    label: '{{ user.name }}'

- name: Create sudoers rule for user
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
  - src: user.sudoers.j2
    dest: /etc/sudoers.d/{{ user_name }}
  loop_control:
    label: '{{ item.dest }}'